version: 0.2

phases:
  pre_build:
    commands:
      - echo "No pre build commands"
  build:
    commands:
      - bash ./scripts/docker-build.sh --EXECUTION_ID $EXECUTION_ID --COMMIT_ID $COMMIT_ID --IMAGE base --ARGS '--push'
  post_build:
    commands:
      - echo "No post build commands"
