version: 0.2

phases:
  install:
    commands:
      - mkdir -vp ~/.docker/cli-plugins/
      - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
      - chmod a+x ~/.docker/cli-plugins/docker-buildx
      - apt-get update
      - apt-get install gcc libpq-dev build-essential -y
      - apt-get install python3-dev --fix-missing -y
      - apt-get install python3-dev python3-pip python3-venv python3-wheel -y
      - pip install --upgrade setuptools
      - pip install cmake
  pre_build:
    commands:
      - docker buildx create --name builder
      - docker buildx use builder
  build:
    commands:
      - bash ./scripts/docker-build.sh --EXECUTION_ID $EXECUTION_ID --COMMIT_ID $COMMIT_ID --IMAGE base --ARGS '--push'
  post_build:
    commands:
      - echo "No post build commands"
