version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to AMmazon ECR...
      - $(aws ecr get-login --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - |
        docker build
        -t $REPOSITORY_URI:latest
        -t $REPOSITORY_URI:$EXECUTION_ID
        -t $REPOSITORY_URI:$COMMIT_ID
        --build-arg $(aws sts get-caller-identity)
        -f Dockerfile.eas-base
        --no-cache .
  post_build:
    commands:
      - echo Building complete on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
