name: on-pr-into-main

permissions:
  contents: read

env:
  PYTHON_VERSION: 3.12

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main

jobs:
  run-pr-checks:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Bootstrap Python app and run tests
        run: |
          set -eu
          make bootstrap
          make test
          make test

  functional-tests:
    name: Invoke Functional Tests
    uses: alphagov/emergency-alerts-functional-tests/.github/workflows/run-functional-tests-pr.yml@main
    with:
      env-default: REPO_BRANCH_UTILS=${{ github.head_ref }}
      pr-description: ${{ github.event.pull_request.body }}
    secrets:
      EAS_GITHUB_RUNNER_RO_TOKEN: ${{ secrets.EAS_GITHUB_RUNNER_RO_TOKEN }}
